### ISSUE TITLE
SAM Local Development: No APIs connected to Lambda functions

### ISSUE THREAD

**Issue by mikylebaksh** [aws-samples/aws-step-functions-plagiarism-demo-dotnetcore#1]
I'm following the readme located in `./AWSStepFunctionsPlagiarismDemo/README.md`. I'm trying to build and run the project on my local environment to get a feel of how step functions and lambdas work together. It's my understanding that SAM CLI should allow to run this entire project entirely on my machine without deploying anything to AWS. I'm very new to AWS and SAM CLI so it might be 
something basic. 

When I try to run the environment locally on my machine, I get the error: 

`Error: Template does not have any APIs connected to Lambda functions`

Please see details below.

OS: Windows 10 Pro
* Followed [Step Functions and Lambda Local](https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-lambda.html) successfully 

## Steps to Reproduce
1. git clone project
2. `cd \aws-step-functions-plagiarism-demo-dotnetcore\AWSStepFunctionsPlagiarismDemo`
2. Issue build command. All projects built, tested, published, and packed successfully: 

**Partial Output:** 
```
PS> ./build.ps1 --target=Package
...
...
========================================         
Pack                                             
========================================         
Packing 'AdminActionTask'...                     
'AdminActionTask' has been packed.               
Packing 'RegisterIncidentTask'...                
'RegisterIncidentTask' has been packed.          
Packing 'ResolveIncidentTask'...                 
'ResolveIncidentTask' has been packed.           
Packing 'ScheduleExamTask'...                    
'ScheduleExamTask' has been packed.              
Packing 'SendNotificationTask'...                
'SendNotificationTask' has been packed.          
Packing 'ValidateExamTask'...                    
'ValidateExamTask' has been packed.              
                                                 
========================================         
Package                                          
========================================         
Package target ran.                              
                                                 
----------------------------------------         
Teardown                                         
----------------------------------------         
Finished running tasks.                          
                                                 
Task                          Duration           
-------------------------------------------------
Setup                         00:00:00.0092101   
Clean                         00:00:00.0626336   
Restore                       00:00:07.6779663   
Build                         00:00:05.9309569   
Test-Unit                     00:00:00.0057104   
Publish                       00:00:11.1256509   
Pack                          00:00:05.9838550   
Package                       00:00:00.0025241   
Teardown                      00:00:00.0022985   
-------------------------------------------------
Total:                        00:00:30.8008058   
```
3. Issue SAM command for local development: `sam local start-api`

**Output:**
```
> sam local start-api
2019-02-14 09:58:44 Found credentials in shared credentials file: ~/.aws/credentials
Error: Template does not have any APIs connected to Lambda functions
```

**Comment by sliedig** [comment]
Hello @mikylebaksh, 

the API integration in this project is not with a Lambda function, but with Step Functions directly. This was an intentional design choice to demonstrate that you could invoke an execution on the state machine directly from API Gateway. 

Also, this project hasn't been tested with Step Functions Local yet as it was released prior to its release. Also not 100% sure, but I'm pretty sure that there isn't full integration with SAM yet either. You can still use it to test the functions and state machines in isolation.

**Comment by mikylebaksh** [comment]
Hey @sliedig,

Thanks for the clarification. Thank you for providing a nice sample project for us to learn from!

**Comment by sliedig** [comment]
You're welcome. I'm working on some updates, so stay tuned.
